name             'apache101'
maintainer       'Nirmal Jonnalagedda'
maintainer_email 'jssnirmal@gmail.com'
license          'all_rights'
description      'Installs/Configures apache101'
long_description 'Installs/Configures apache101'
version          '0.1.0'
